version: "3.4"
services:
  app:
    container_name: nginx-proxy-manager_web
    image: 'alunicero/nginx-proxy-manager:raspi1.0'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    container_name: nginx-proxy-manager_web
    image: 'alunicero/mariadb:raspi1.0'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql


#
#docker-compose up -d
#
#URL = (TU IP) : (81)
#
#Default Admin User:
#Email:    admin@example.com
#Password: changeme
#
#
#
#