version: '3.4'
kodi:
    container_name: kodi
    image: linuxserver/kodi-headless
    restart: always
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europa/España
    volumes:
      - ./kodi:/config/.kodi
    ports:
      - 8080:8080
      - 9090:9090
      - "9777:9777/udp"