version: "3.4"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./path/to/appdata/config:/config
    ports:
      - 9999:80
      #- 443:443
    restart: unless-stopped
